#include "avr_chipinfo_set.h"

#define ChipInfo(n, r) {n, sizeof(r)/sizeof(r[0]), r}

struct AvrChipIoRegInfo chip_Atmega328P_Ioregs[] = {
    {0x0003, "PINB", "Port B Input Pins Address"},
    {0x0004, "DDRB", "Port B Data Direction Register"},
    {0x0005, "PORTB", "Port B Data Register"},
    {0x0006, "PINC", "Port C Input Pins Address"},
    {0x0007, "DDRC", "Port C Data Direction Register"},
    {0x0008, "PORTC", "Port C Data Register"},
    {0x0009, "PIND", "Port D Input Pins Address"},
    {0x000A, "DDRD", "Port D Data Direction Register"},
    {0x000B, "PORTD", "Port D Data Register"},
    {0x0015, "TIFR0", "Timer/Counter0 Interrupt Flag Register"},
    {0x0016, "TIFR1", "Timer/Counter1 Interrupt Flag Register"},
    {0x0017, "TIFR2", "Timer/Counter2 Interrupt Flag Register"},
    {0x001B, "PCIFR", "Pin Change Interrupt Flag Register"},
    {0x001C, "EIFR", "External Interrupt Flag Register"},
    {0x001D, "EIMSK", "External Interrupt Mask Register"},
    {0x001E, "GPIOR0", "General Purpose I/O Register 0"},
    {0x001F, "EECR", "The EEPROM Control Register"},
    {0x0020, "EEDR", "EEPROM Data Register"},
    {0x0021, "EEARL", "EEPROM Address Register Low Byte"},
    {0x0022, "EEARH", "The EEPROM Address Register High"},
    {0x0023, "GTCCR", "General Timer/Counter Control Register"},
    {0x0024, "TCCR0A", "Timer/Counter Control Register A"},
    {0x0025, "TCCR0B", "Timer/Counter Control Register B"},
    {0x0026, "TCNT0", "Timer/Counter0 (8 Bit)"},
    {0x0027, "OCR0A", "Timer/Counter0 Output Compare Register A"},
    {0x0028, "OCR0B", "Timer/Counter0 Output Compare Register B"},
    {0x002A, "GPIOR1", "General Purpose I/O Register 1"},
    {0x002B, "GPIOR2", "General Purpose I/O Register 2"},
    {0x002C, "SPCR0", "SPI Control Register"},
    {0x002D, "SPSR0", "SPI Status Register"},
    {0x002E, "SPDR0", "SPI Data Register"},
    {0x0030, "ACSR", "Analog Comparator Control and Status Register"},
    {0x0031, "DWDR", "debugWire Data Register"},
    {0x0033, "SMCR", "Sleep Mode Control Register"},
    {0x0034, "MCUSR", "MCU Status Register"},
    {0x0035, "MCUCR", "MCU Control Register"},
    {0x0037, "SPMCSR", "Store Program Memory Control Register"},
    {0x003D, "SPL", "Stack Pointer Low"},
    {0x003E, "SPH", "Stack Pointer High"},
    {0x003F, "SREG", "Status Register"},
    {0x0040, "WDTCSR", "Watchdog Timer Control Register"},
    {0x0041, "CLKPR", "Clock Prescale Register"},
    {0x0044, "PRR", "Power Reduction Register"},
    {0x0046, "OSCCAL", "Oscillator Calibration Register"},
    {0x0048, "PCICR", "Pin Change Interrupt Control Register"},
    {0x0049, "EICRA", "External Interrupt Control Register A"},
    {0x004B, "PCMSK0", "Pin Change Mask Register 0"},
    {0x004C, "PCMSK1", "Pin Change Mask Register 1"},
    {0x004D, "PCMSK2", "Pin Change Mask Register 2"},
    {0x004E, "TIMSK0", "Timer/Counter Interrupt Mask Register"},
    {0x004F, "TIMSK1", "Timer/Counter1 Interrupt Mask Register"},
    {0x0050, "TIMSK2", "Timer/Counter2 Interrupt Mask Register"},
    {0x0058, "ADCL", "ADC Data Register Low byte"},
    {0x0059, "ADCH", "ADC Data Register High byte"},
    {0x005A, "ADCSRA", "ADC Control and Status Register A"},
    {0x005B, "ADCSRB", "ADC Control and Status Register B"},
    {0x005C, "ADMUX", "ADC Multiplexer Selection Register"},
    {0x005E, "DIDR0", "Digital Input Disable Register 0"},
    {0x005F, "DIDR1", "Digital Input Disable Register 1"},
    {0x0060, "TCCR1A", "Timer/Counter1 Control Register A"},
    {0x0061, "TCCR1B", "Timer/Counter1 Control Register B"},
    {0x0062, "TCCR1C", "Timer/Counter1 Control Register C"},
    {0x0064, "TCNT1L", "Timer/Counter1 - Counter Register Low Byte"},
    {0x0065, "TCNT1H", "Timer/Counter1 - Counter Register High Byte"},
    {0x0066, "ICR1L", "Timer/Counter1 - Input Capture Register Low Byte"},
    {0x0067, "ICR1H", "Timer/Counter1 - Input Capture Register High Byte"},
    {0x0068, "OCR1AL", "Timer/Counter1 - Output Compare Register A Low Byte"},
    {0x0069, "OCR1AH", "Timer/Counter1 - Output Compare Register A High Byte"},
    {0x006A, "OCR1BL", "Timer/Counter1 - Output Compare Register B Low Byte"},
    {0x006B, "OCR1BH", "Timer/Counter1 - Output Compare Register B High Byte"},
    {0x0090, "TCCR2A", "Timer/Counter Control Register A"},
    {0x0091, "TCCR2B", "Timer/Counter Control Register B"},
    {0x0092, "TCNT2", "Timer/Counter2 (8 Bit)"},
    {0x0093, "OCR2A", "Timer/Counter2 Output Compare Register A"},
    {0x0094, "OCR2B", "Timer/Counter2 Output Compare Register B"},
    {0x0096, "ASSR", "Asynchronous Status Register"},
    {0x0098, "TWBR", "2-wire Serial Interface Bit Rate Register"},
    {0x0099, "TWSR", "TWI Status Register"},
    {0x009A, "TWAR", "TWI (Slave) Address Register"},
    {0x009B, "TWDR", "2-wire Serial Interface Data Register"},
    {0x009C, "TWCR", "TWI Control Register"},
    {0x009D, "TWAMR", "TWI (Slave) Address Mask Register"},
    {0x00A4, "UBRR0L", "USART0 Baud Rate Register Low Byte"},
    {0x00A5, "UBRR0H", "USART0 Baud Rate Register High Byte"},
    {0x00A6, "UDR0", "USART0 I/O Data Register"}
};

struct AvrChipInfo AVR_ChipInfo_Set[] = {
    ChipInfo("ATmega328P", chip_Atmega328P_Ioregs)
};

int AVR_TOTAL_CHIPINFOS = (sizeof(AVR_ChipInfo_Set)/sizeof(AVR_ChipInfo_Set[0]));
